name: Build, test, release

#on:
  #pull_request:
    #branches:
      #- main
on: [push]
#on:
  #push:
    #branches: [ "main", "master" ]

jobs:
  call-build:
    uses: haridusministeerium/workflows/.github/workflows/py-build-publish-app.yml@master
    secrets: inherit
